---
- name: Allow OpenSSH through UFW
  ufw:
    rule: allow
    name: OpenSSH

- name: Allow HTTP through UFW
  ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Allow HTTPS through UFW
  ufw:
    rule: allow
    port: '443'
    proto: tcp

- name: Enable UFW
  ufw:
    state: enabled
    policy: deny
