---
- name: Install PHP and extensions
  apt:
    name:
      - php-fpm
      - php-mysql
      - php-curl
      - php-gd
      - php-mbstring
      - php-xml
      - php-xmlrpc
      - php-soap
      - php-intl
      - php-zip
    state: present
    update_cache: yes

- name: Ensure PHP-FPM is running
  service:
    name: php8.3-fpm
    state: started
    enabled: yes
